name: 网易云音乐签到

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main 
  schedule:
    - cron: '0 23 * * *'
 # watch:
 #   types: started


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v3
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - name: 初始化Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: 开始
      run: |
        pip install -r requirements.txt
        #pmode='${{ secrets.PMODE }}'
        #pkey='${{ secrets.PKEY }}'
        #user='${{ secrets.USER }}'
        #pwd='${{ secrets.PWD }}'
        #step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
       # ${pmode}
       ## ${pkey}
       # ${user}
       # ${pwd}
       # ${step}
        EOF
