name: 网易云音乐签到

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: install pip packages
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
    - name: 开始签到
      run: |   
        python3 main.py
