name: 网易云音乐签到

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: install pip packages
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
    - name: 开始签到
      env: 
        uin: ${{ secrets.ACCOUNT }}
        pwd: ${{ secrets.PASSWORD }}
        al_id: ${{ secrets.ALID }}
        countrycode: ${{ secrets.COUNTRYCODE }}
        api: ${{ secrets.API }}
        md5Switch: ${{ secrets.MD5SWITCH }}
        peopleSwitch: ${{ secrets.PEOPLESWITCH }}
        pushmethod: ${{ secrets.PUSHMETHOD }}
        sckey: ${{ secrets.SCKEY }}
        ppkey: ${{ secrets.PPKEY }}
        appToken: ${{ secrets.APPTOKEN }}
        wxpusheruid: ${{ secrets.WXPUSHRUID }}
        barkServer: ${{ secrets.BARKSERVER }}
        barkKey: ${{ secrets.BARKKEY }}
      run: 
        python3 main.py
